### ISSUE TITLE
bug:  Build logs don't show

### ISSUE THREAD

**Issue by fior-di-latte** [invertase/globe#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### CLI Version

v0.0.11

### Project ID

129a0782-db12-4402-97f7-0a99a6f591cb

### Description

When triggering a build over the CLI,  the build logs are not shown:
```
globe build-logs --deployment="129a0782-db12-4402-97f7-0a99a6f591cb"
Globe API Error.
There was an issue calling the Globe API, please try again.
 Use verbose mode using the --verbose flag for more details.
Unhandled exception:
Instance of 'ApiException'
#0      GlobeApi._handleResponse (package:globe_cli/src/utils/api.dart:62:7)
#1      GlobeApi.getDeployment (package:globe_cli/src/utils/api.dart:205:22)
<asynchronous suspension>
#2      BuildLogsCommand.run (package:globe_cli/src/commands/build_logs_command.dart:39:24)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      GlobeCliCommandRunner.run (package:globe_cli/src/command_runner.dart:108:14)
<asynchronous suspension>
#5      main (file:///Users/ftodaP/.pub-cache/hosted/pub.dev/globe_cli-0.0.11/bin/globe.dart:15:5)
<asynchronous suspension>
```
On globe.dev, the logs also don't show up.

### Steps to reproduce

I guess it is dependent on the error type? I'm not sure how to reproduce.

### Expected behavior

I would expect to see the logs.

**Comment by codekeyz** [comment]
@fior-di-latte Could you run this same command with `--verbose` flag and share the output?

**Comment by fior-di-latte** [comment]
Oh, my bad, here it is, with the `verbose` flag

```
globe build-logs --deployment="129a0782-db12-4402-97f7-0a99a6f591cb" --verbose
Verbose logging enabled.
API Request: GET /user/orgs
API Request: GET /orgs/d4e0e6af-0cb9-43e2-9807-8b5e3ccdc3f5/projects
Validated scope: fior-di-latte/intellivend
API Request: GET /orgs/d4e0e6af-0cb9-43e2-9807-8b5e3ccdc3f5/projects/fe3b0b27-3151-4fa1-bcdd-80e7d8cd1f94/deployments/129a0782-db12-4402-97f7-0a99a6f591cb
Globe API Error.
There was an issue calling the Globe API, please try again.
 Use verbose mode using the --verbose flag for more details.
If this issue persists please contact support and provide these logs.
---
"Status Code": 404

"Headers":
connection: keep-alive
date: Mon, 03 Jun 2024 09:48:57 GMT
transfer-encoding: chunked
content-encoding: gzip
vary: Accept-Encoding
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
cf-ray: 88dec53d0aaf717e-DUS
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=izP6G1R3LiRiomtLSoD2c8peGKhvh4tfdMR7%2FDckBPiRGG3WgAWEQpkM7YgqMzHJ1buO85%2Fe%2FyO1NJ2BKjWtpgj9aZSBUh6y9wGD55QxYPA6SEif7yrHbuu4WTc%3D"}],"group":"cf-nel","max_age":604800}
content-type: application/json
server: cloudflare

"Body":
{"title":"Resource Not Found","message":"The requested resource was not found."}
Unhandled exception:
Instance of 'ApiException'
#0      GlobeApi._handleResponse (package:globe_cli/src/utils/api.dart:62:7)
#1      GlobeApi.getDeployment (package:globe_cli/src/utils/api.dart:205:22)
<asynchronous suspension>
#2      BuildLogsCommand.run (package:globe_cli/src/commands/build_logs_command.dart:39:24)
<asynchronous suspension>
#3      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
<asynchronous suspension>
#4      GlobeCliCommandRunner.run (package:globe_cli/src/command_runner.dart:108:14)
<asynchronous suspension>
#5      main (file:///Users/ftodaP/.pub-cache/hosted/pub.dev/globe_cli-0.0.11/bin/globe.dart:15:5)
<asynchronous suspension>
```

**Comment by codekeyz** [comment]
@fior-di-latte I can confirm this works. 

I'm closing this for now. Feel free to re-open this if issue still persists.
